"""Persona-driven student BOTS that generate real demo data through the live engine.

WHY (owner direction, 2026-05-30): instead of seeding hand-set demo rows, we want SOLID
data that looks like real students actually used the app — generated by driving the
existing persona behavioral simulators (``app.personas`` Layer 3 — Priya/Sam/Nate/Cleo/
Hugo) through the REAL turn loop, so every mastery/turn number comes from the real
verify→mastery→persist path. The teacher dashboard then reads genuine students, and the
whole plumbing is exercised end-to-end.

HONEST SCOPE (confirmed with the model lane, 2026-05-30): only the FIVE fraction-
foundation KCs are content-complete (``EQUIVALENCE / COMMON_DENOMINATOR / ADDITION_UNLIKE
/ SUBTRACTION_UNLIKE / NUMBER_LINE_PLACEMENT``), and the five personas only configure
knowledge for those. So the bots generate **fraction-lesson data only** — enough to
populate the dashboard and validate the real plumbing, but NOT weak-KC or non-fraction
data (that is gated on the Grade-6 content build). The bot framework generalizes for free
once that content + grade-6 persona configs exist; it simply has nothing to drive on the
other 41 KCs today.

DETERMINISTIC, NO LLM (CLAUDE.md §8.1/§8.3). The driving is pure code:
  - Layer 2 = each persona's hand-written knowledge state (KCs known, misconceptions, hint
    probability).
  - Layer 3 (``personas/simulator.simulate_action``) = a pure ``(persona, problem) →
    action`` function. Wrong answers come from the SymPy misconception generators, not
    invention.
  - The bot answers whatever problem the REAL scheduler serves (``SessionStore`` picks the
    KC/representation/difficulty), so the data reflects the real adaptive turn loop.
The LLM (Layer 4) is never reached here — bots produce every behavioral number with the
voice/hint/predictor providers off.

THE TWO HALVES
--------------
1. Data generation (THIS module, backend): ``run_student_bot`` drives one persona through
   ``SessionStore.process_turn`` with persistence ON → genuine Learner/Session/Turn/
   MasteryState rows; ``seed_demo_class`` runs every profile and rosters them to the demo
   teacher. Both idempotent on the stable per-bot ``session_id``.
2. Visual-QA sweep (CROSS-LANE, frontend/e2e): a Playwright pass that screenshots every
   screen on this real data. That harness is T3's lane (T1 must not touch ``frontend/``);
   this module owns only the data the sweep runs against.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from uuid import NAMESPACE_URL, uuid5

from sqlalchemy.orm import Session as OrmSession
from sqlalchemy.orm import sessionmaker
from sympy import Rational

from app.api.schemas import ActionType, TurnRequest
from app.api.service import SessionStore
from app.auth.passwords import hash_password, hash_pin
from app.db import repositories as repo
from app.domain.curriculum import all_units
from app.domain.knowledge_components import KnowledgeComponentId
from app.personas.persona_config import PersonaConfig
from app.personas.registry import get_persona
from app.personas.simulator import simulate_action
from app.tutor.session import routing_choices


@dataclass(frozen=True)
class StudentBotProfile:
    """A bot student: a persona + the Turn-0 route it plays + its intended dashboard bucket.

    The bot starts a session on ``route_key`` (a Turn-0 menu key, e.g. ``"combine"``) — that
    fixes the lesson's goal KC server-side — and the real scheduler then serves problems the
    persona answers via the Layer-3 simulator. The persona's fixed behavior determines the
    outcome, so each profile is designed to land in a known dashboard category.

    ``session_id`` is the stable external key that makes a re-run idempotent (it maps to the
    same Learner row, no duplicates). ``intended_category`` records the bucket
    (``"struggling"`` / ``"needs_attention"`` / ``"on_track"``) the persona is DESIGNED to
    produce — the AUTHORITATIVE category is always computed server-side by the teacher
    service from the persisted turns/mastery; this field is the design intent + the QA
    expectation, not a stored value. ``max_turns`` caps a non-mastering bot's session (a
    persona that never confirms mastery would otherwise loop forever); a mastering bot stops
    early when the lesson completes.
    """

    persona: PersonaConfig
    display_name: str
    session_id: str
    route_key: str
    intended_category: str
    max_turns: int = 24


# The demo class: one bot per fraction persona, each routed to a lesson its persona engages
# with. ``intended_category`` is the bucket the LIVE teacher service actually places the bot in,
# VERIFIED by seeding a DB and reading the roster (not a guess). This is the spread the FIVE
# real personas produce — we do not fabricate extra students to pad the buckets (CLAUDE.md §5:
# report the real scope).
#
# VERIFIED SPREAD: on_track × 3 (Cora, Priya, Hugo) + struggling × 3 (Sam, Nate, Cleo), covering
# the STUCK and REPEATED_MISCONCEPTION alert kinds. Capable Cora is the genuinely-competent learner
# (the §4.1 positive control, cora.py) and the ONLY bot who confirms mastery → she gives the demo a
# real top student with progress > 0 instead of an all-0% roster. One honest finding still worth
# knowing (flagged to the owner + the T1/T2/T3 channel, not worked around):
#   - Hugo lands on_track though he is pedagogically needs_attention: he only answers correctly WITH
#     a hint (zero unscaffolded correct), but the teacher alert rules don't flag the hint-dependency
#     signature, so no alert fires. That is a real gap in the alert layer (alerts.py, T2's lane),
#     flagged for them — not gamed here. (The four other negative-control personas never confirm
#     mastery, by design — they are the cases that defeat fake mastery; Cora is the case that earns
#     it.)
DEMO_BOT_PROFILES: tuple[StudentBotProfile, ...] = (
    StudentBotProfile(
        persona=get_persona("capable_cora"),
        display_name="Capable Cora",
        session_id="bot-capable-cora",
        route_key="combine",
        # The positive control: genuine understanding → confirms mastery → real progress.
        intended_category="on_track",
    ),
    StudentBotProfile(
        persona=get_persona("procedure_priya"),
        display_name="Procedure Priya",
        session_id="bot-procedure-priya",
        route_key="combine",
        # Procedurally fluent (no alerts) but fails the transfer probe → never confirmed.
        intended_category="on_track",
    ),
    StudentBotProfile(
        persona=get_persona("hint_hunter_hugo"),
        display_name="Hint-hunter Hugo",
        session_id="bot-hint-hunter-hugo",
        route_key="combine",
        # Pedagogically needs_attention (hint-dependent, 0 unscaffolded correct), but the alert
        # rules don't surface that today, so the live dashboard places him on_track (finding #2).
        intended_category="on_track",
    ),
    StudentBotProfile(
        persona=get_persona("surface_sam"),
        display_name="Surface Sam",
        session_id="bot-surface-sam",
        route_key="combine",
        intended_category="struggling",
    ),
    StudentBotProfile(
        persona=get_persona("natural_number_nate"),
        display_name="Natural-number Nate",
        session_id="bot-natural-number-nate",
        route_key="same_amount",
        intended_category="struggling",
    ),
    StudentBotProfile(
        persona=get_persona("click_through_cleo"),
        display_name="Click-through Cleo",
        session_id="bot-click-through-cleo",
        route_key="combine",
        intended_category="struggling",
    ),
)


def _answer_str(value: Rational | bool | None) -> str:
    """Render the simulator's answer as the wire string the verifier parses.

    The Layer-3 simulator returns a SymPy ``Rational`` for a numeric item or a ``bool`` for
    a yes/no item (``None`` only on a no-answer EXPLAIN turn, which the ANSWER-only bot loop
    never hits). The turn loop's ``submitted_answer`` is the raw string the domain verifier
    parses: ``str(Rational(7, 12)) == "7/12"`` round-trips through ``_parse_to_rational``,
    and ``str(True) == "True"`` / ``str(False) == "False"`` round-trip through
    ``_parse_to_bool`` (case-insensitive 'true'/'false'). So the bot's verdict is identical
    to ``run_persona`` handing the verifier the value directly. ``None`` → ``""`` (wrong,
    never a crash).
    """
    return "" if value is None else str(value)


def _goal_kc_for_route(route_key: str) -> KnowledgeComponentId:
    """The goal KC a Turn-0 route launches into (the single-source-of-truth routing table)."""
    for option in routing_choices():
        if option.key == route_key:
            return option.routes_to
    raise ValueError(f"unknown route_key: {route_key!r}")


def _unit_slug_for_kc(kc: KnowledgeComponentId) -> str | None:
    """The catalog unit slug whose lessons teach ``kc``, or ``None`` if no unit covers it.

    Derived from the frozen curriculum catalog (``all_units``) so the assignment tracks the
    real unit/lesson structure rather than a hardcoded slug. ``CatalogLesson.kc_id`` is the
    plain KC string, so we compare against ``kc.value``.
    """
    for unit in all_units():
        for lesson in unit.lessons:
            if lesson.kc_id == kc.value:
                return unit.slug
    return None


def _already_seeded(session_factory: sessionmaker[OrmSession], session_id: str) -> bool:
    """Has this bot already been driven through the turn loop (idempotency guard)?

    True when a learner for ``session_id`` exists AND has persisted turns — meaning a prior
    ``run_student_bot`` already drove and recorded this bot's session. We then skip re-driving
    (which would append a duplicate Session + Turn history) and only re-assert the roster /
    assignment, which are themselves idempotent.
    """
    with session_factory() as db:
        learner = repo.get_learner(db, session_id)
        if learner is None:
            return False
        return bool(repo.load_turns_for_learner(db, learner.id))


def _drive_turns(profile: StudentBotProfile, session_factory: sessionmaker[OrmSession]) -> None:
    """Drive one persona through the REAL turn loop with persistence ON.

    Starts a session on the profile's route (pinned to ``profile.session_id`` so the problem
    walk is reproducible and the run is idempotent), then loops: read the live ``Problem`` the
    store is showing → ask the Layer-3 simulator for the persona's deterministic action →
    submit it through ``SessionStore.process_turn`` (which verifies, updates mastery, applies
    the policy, serves the next problem, and persists the Turn + MasteryState rows). Stops when
    the lesson completes (a mastering persona confirmed the KC), the store serves no next
    problem, or ``max_turns`` is reached (the cap that bounds a never-mastering persona).

    The bot store runs with NO predictor/voice/hint providers and the proactive arm OFF: bots
    are pure behavioral data, so the LLM/HelpNeed layers stay out (CLAUDE.md §8.1) and the run
    is deterministic.
    """
    store = SessionStore(session_factory=session_factory)
    started = store.start(profile.route_key, session_id=profile.session_id)
    surface_state = started.surface_state
    for _ in range(profile.max_turns):
        problem = store.current_problem(started.session_id)
        if problem is None:
            break
        action = simulate_action(profile.persona, problem)
        request = TurnRequest(
            session_id=started.session_id,
            problem_id=problem.problem_id,
            action=ActionType.SUBMIT_ANSWER,
            submitted_answer=_answer_str(action.submitted_answer),
            surface_state=surface_state,
            latency_ms=max(0, round(action.think_time_seconds * 1000)),
            hint_used=action.requested_hint,
        )
        response = store.process_turn(request)
        if response.lesson_complete or response.next_problem is None:
            break
        surface_state = response.next_surface_state


def _roster_and_assign(
    profile: StudentBotProfile,
    session_factory: sessionmaker[OrmSession],
    *,
    teacher_id: int,
    now: datetime,
) -> int:
    """Roster the bot's learner to the teacher (+ assign its unit best-effort); return its id.

    Rostering (``add_student_to_roster``) is what makes the bot appear on the teacher's
    dashboard. We also label the learner with a readable bot email so the dashboard's
    name (the email local-part, ``teacher_service._display_name``) reads e.g.
    ``"procedure-priya"`` instead of ``"Student N"``, and assign the unit that teaches the
    bot's goal KC as a steering hint. All three are idempotent (roster/assignment upsert on
    their unique keys), so re-running is safe. Unit assignment is best-effort: if the curriculum
    is unseeded and the unit row is absent, we skip it rather than fail the seed.
    """
    with session_factory() as db:
        learner = repo.get_or_create_learner(db, profile.session_id)
        db.flush()
        if not learner.email:
            learner.email = _bot_email(profile.display_name)
        repo.add_student_to_roster(db, teacher_id, learner.id)
        slug = _unit_slug_for_kc(_goal_kc_for_route(profile.route_key))
        if slug is not None:
            unit = repo.get_unit(db, slug)
            if unit is not None:
                repo.assign_unit(
                    db,
                    teacher_id=teacher_id,
                    student_id=learner.id,
                    unit_id=unit.id,
                    now=now,
                )
        db.commit()
        return learner.id


def _bot_email(display_name: str) -> str:
    """A readable, clearly-synthetic email for a bot, so the dashboard shows a persona label.

    The teacher dashboard derives a student's display name from the email local-part, so a
    slug of the persona name (e.g. ``"procedure-priya"``) renders a recognizable label while
    the ``@bots.whollymath.demo`` domain marks the row as a generated bot, not a real account.
    """
    slug = "-".join(display_name.lower().split())
    return f"{slug}@bots.whollymath.demo"


def run_student_bot(
    profile: StudentBotProfile,
    session_factory: sessionmaker[OrmSession],
    *,
    teacher_id: int,
    now: datetime,
) -> int:
    """Drive one persona bot through the REAL turn loop with persistence; return its learner id.

    Idempotent on ``profile.session_id``: the first run drives the turns (persisting genuine
    Session/Turn/MasteryState rows) and rosters the learner to ``teacher_id``; a re-run detects
    the already-seeded session, skips re-driving (so no duplicate turns), and only re-asserts
    the (idempotent) roster + assignment. Returns the bot's learner id either way.
    """
    if not _already_seeded(session_factory, profile.session_id):
        _drive_turns(profile, session_factory)
    return _roster_and_assign(profile, session_factory, teacher_id=teacher_id, now=now)


def seed_demo_class(
    session_factory: sessionmaker[OrmSession],
    *,
    now: datetime,
) -> list[int]:
    """Run every demo bot profile and roster them to the shared demo teacher; return their ids.

    Idempotent end-to-end: ``get_or_create_demo_teacher`` keys on a fixed session id (one
    teacher), and each ``run_student_bot`` maps to a stable learner — so re-running yields the
    same demo class (same teacher, same students, same turns), stable across reboots. Produces
    real numbers via the live turn loop, not hand-set rows.
    """
    with session_factory() as db:
        teacher = repo.get_or_create_demo_teacher(db)
        db.commit()
        teacher_id = teacher.id
    return [
        run_student_bot(profile, session_factory, teacher_id=teacher_id, now=now)
        for profile in DEMO_BOT_PROFILES
    ]


# ─── Demo PARENT + children (parent dashboard) ────────────────────────────────────────────────
# The parent surface mirrors the teacher one: a household of real CHILD accounts with genuine,
# persona-driven progress, so the parent dashboard roster + per-child drill-in read live data
# (api/parent.ts), not fixtures. A child is a normal learner, so we drive the same personas through
# the real turn loop against the child's ``child:<public_id>`` session — identical to the child
# logging in and practicing. Two children give a clear spread (one thriving, one struggling).
DEMO_PARENT_EMAIL = "demo.parent@whollymath.dev"
DEMO_PARENT_PASSWORD = "demo-parent-pw1"  # noqa: S105 — a public demo credential, not a secret.
DEMO_CHILD_PIN = "8245"  # non-trivial demo PIN (not a sequential/common one)


@dataclass(frozen=True)
class DemoChildProfile:
    """A demo child: a persona to drive + the login identity its account is created with."""

    persona: PersonaConfig
    display_name: str
    username: str
    route_key: str


DEMO_CHILD_PROFILES: tuple[DemoChildProfile, ...] = (
    DemoChildProfile(get_persona("capable_cora"), "Cora", "cora-demo", "combine"),
    DemoChildProfile(get_persona("surface_sam"), "Sam", "sam-demo", "combine"),
)


def _demo_child_public_id(username: str) -> str:
    """A STABLE public id for a demo child, so re-seeding maps to the same child (idempotent).

    ``create_child`` takes the public id from the caller; a random uuid4 each run would mint a new
    child every boot. uuid5 over a fixed namespace + the username is deterministic, so the child's
    account, drill-in URL, and persisted progress are stable across reboots."""
    return uuid5(NAMESPACE_URL, f"whollymath-demo-child:{username}").hex


def seed_demo_parent(
    session_factory: sessionmaker[OrmSession],
    *,
    now: datetime,
) -> tuple[int, list[int]]:
    """Create the demo parent + children, drive their personas; return (parent_id, child_ids).

    Idempotent end-to-end: the parent is keyed on its email (one row), each child on a stable
    ``public_id`` (one row), and ``run``-style turn driving is skipped once a child already has
    persisted turns. So re-running yields the same household with the same progress. The demo parent
    is created email-verified so its children are immediately live (the verification gate is the
    real-signup consent anchor, not relevant to the seeded demo account)."""
    with session_factory() as db:
        parent = repo.get_parent_by_email(db, DEMO_PARENT_EMAIL)
        if parent is None:
            parent = repo.create_parent_with_password(
                db, email=DEMO_PARENT_EMAIL, password_hash=hash_password(DEMO_PARENT_PASSWORD)
            )
            parent.email_verified = True  # demo parent is pre-verified so children go live
            db.commit()
        parent_id = parent.id

    child_ids: list[int] = []
    for profile in DEMO_CHILD_PROFILES:
        public_id = _demo_child_public_id(profile.username)
        with session_factory() as db:
            child = repo.get_child_for_parent(db, parent_id, public_id)
            if child is None:
                child = repo.create_child(
                    db,
                    parent_id=parent_id,
                    public_id=public_id,
                    display_name=profile.display_name,
                    grade_level=6,
                    locale="en",
                    child_username=profile.username,
                    pin_hash=hash_pin(DEMO_CHILD_PIN),
                )
                db.commit()
            child_ids.append(child.id)
        # Drive the persona through the real turn loop AS this child (its child:<public_id>
        # session), so the child accrues genuine mastery/turns. Reuses the class-bot driving path.
        bot = StudentBotProfile(
            persona=profile.persona,
            display_name=profile.display_name,
            session_id=f"child:{public_id}",
            route_key=profile.route_key,
            intended_category="on_track",
        )
        if not _already_seeded(session_factory, bot.session_id):
            _drive_turns(bot, session_factory)
    return parent_id, child_ids


__all__ = [
    "DEMO_BOT_PROFILES",
    "DEMO_CHILD_PROFILES",
    "DemoChildProfile",
    "StudentBotProfile",
    "run_student_bot",
    "seed_demo_class",
    "seed_demo_parent",
]
