"""Persona-driven student BOTS that generate real data + a visual-QA sweep — STUB (deferred).

⚠️ STUB ONLY (owner direction, 2026-05-30): the design is captured here so it is ready to build
at the END of the backend backlog. Nothing in this module is wired yet — every entry point raises
``NotImplementedError``. Do not import it on a hot path.

WHY (owner intent): instead of seeding hand-set demo rows, we want SOLID data that looks like real
students actually used the app — generated by driving the existing persona behavioral simulators
(``app.personas`` Layer 3 — Priya/Sam/Nate/Cleo/Hugo) through the REAL engine, so every
mastery/turn number comes from the real verify→mastery path. Then a Playwright pass screenshots
EVERY screen on that real data so the owner can eyeball the whole product and spot anything missing
or broken.

THE TWO HALVES
--------------
1. Data generation (THIS lane, T1/backend): a runner that, for each ``StudentBotProfile``, starts a
   real session and loops ``simulate_action`` (the persona's deterministic decision over the real
   Layer-1 ``Problem``) → the real turn loop with persistence ON (``SessionStore.process_turn`` +
   a DB), producing genuine ``Learner``/``Session``/``Turn``/``MasteryState`` rows. The bots are
   then rostered to a teacher so the dashboard reads them as real students. Reuses everything that
   already exists; what is missing is only the persistence/roster wiring and the profile list.

2. Visual-QA sweep (CROSS-LANE — needs T2/T3): a Playwright script that logs in (learner + the
   demo teacher), walks every route (units → unit → lesson → tutor turn states → course map;
   teacher roster → drill-in → assign), and saves a screenshot of each, so missing/broken screens
   surface at a glance. The Playwright harness lives in the frontend/e2e lane — COORDINATE with
   T2/T3 before building it (T1 must not touch ``frontend/``). This module owns only the data the
   sweep runs against.

BUILD ORDER WHEN UN-STUBBING (end of backlog):
  a. ``StudentBotProfile`` list spanning every ranked category (struggling/needs-attention/
     on-track) and every alert kind — mirror the shapes lane T2 already authored in
     ``frontend/src/api/teacherDemo.ts`` so the swap is data-only.
  b. ``run_student_bot`` — drive one persona through ``SessionStore`` with persistence, return the
     created learner id. Idempotent on a stable per-bot session id.
  c. ``seed_demo_class`` — run every profile + roster them to the teacher; idempotent.
  d. Hand the populated DB to the (cross-lane) Playwright sweep.

TODO(hr, 2026-05-30): un-stub at end of backend backlog; coordinate the Playwright half with T2/T3.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

from sqlalchemy.orm import Session as OrmSession
from sqlalchemy.orm import sessionmaker

from app.personas.persona_config import PersonaConfig


@dataclass(frozen=True)
class StudentBotProfile:
    """A bot student: a persona + a display name + the lesson sequence it should play (STUB).

    When un-stubbed, ``sequence`` is the list of (KC, surface) problem specs the bot is driven
    through (the same ``ProblemSpec`` shape ``app.personas.run`` already uses), chosen so the
    resulting mastery/alerts land the bot in its intended dashboard category.
    """

    persona: PersonaConfig
    display_name: str
    session_id: str  # stable external key so re-running is idempotent (no duplicate learners)


def run_student_bot(
    profile: StudentBotProfile,
    session_factory: sessionmaker[OrmSession],
    *,
    teacher_id: int,
    now: datetime,
) -> int:
    """Drive one persona bot through the REAL turn loop with persistence; return its learner id.

    STUB. Will: start a session for ``profile.session_id``, loop ``simulate_action`` over the
    profile's problem sequence calling the real ``SessionStore.process_turn`` (persistence ON), and
    roster the resulting learner to ``teacher_id`` — so the data is genuine, not hand-set.
    """
    raise NotImplementedError(
        "student_bots is a deferred stub (owner direction 2026-05-30); un-stub at end of backlog."
    )


def seed_demo_class(
    session_factory: sessionmaker[OrmSession],
    *,
    teacher_id: int,
    now: datetime,
) -> list[int]:
    """Run every demo bot profile and roster them to a teacher; return the learner ids (STUB).

    STUB. Idempotent: re-running maps each bot to the same learner (stable session ids), so the
    demo class is stable across reboots. Produces real numbers via ``run_student_bot``.
    """
    raise NotImplementedError(
        "student_bots is a deferred stub (owner direction 2026-05-30); un-stub at end of backlog."
    )


__all__ = ["StudentBotProfile", "run_student_bot", "seed_demo_class"]
