"""learner google_sub

Revision ID: 1d435502e4db
Revises: a32e6e852503
Create Date: 2026-05-28 16:35:23.022077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d435502e4db'
down_revision: Union[str, Sequence[str], None] = 'a32e6e852503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learner', sa.Column('google_sub', sa.String(length=255), nullable=True))
    op.add_column('learner', sa.Column('email', sa.String(length=320), nullable=True))
    op.create_index(op.f('ix_learner_google_sub'), 'learner', ['google_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learner_google_sub'), table_name='learner')
    op.drop_column('learner', 'email')
    op.drop_column('learner', 'google_sub')
    # ### end Alembic commands ###
