"""interaction_event

Revision ID: a32e6e852503
Revises: f3426185eb03
Create Date: 2026-05-28 16:18:27.839351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a32e6e852503'
down_revision: Union[str, Sequence[str], None] = 'f3426185eb03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('learner_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('client_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_event_event_type'), 'interaction_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_interaction_event_learner_id'), 'interaction_event', ['learner_id'], unique=False)
    op.create_index(op.f('ix_interaction_event_session_id'), 'interaction_event', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_event_session_id'), table_name='interaction_event')
    op.drop_index(op.f('ix_interaction_event_learner_id'), table_name='interaction_event')
    op.drop_index(op.f('ix_interaction_event_event_type'), table_name='interaction_event')
    op.drop_table('interaction_event')
    # ### end Alembic commands ###
