"""unit cluster columns nullable + seed the curriculum catalog

Revision ID: b4f7c9a2e1d8
Revises: c1a7b2f4d9e0
Create Date: 2026-05-30

Slice DAT.4 (with the Part-1 schema fix). Two coupled changes, in order:

  1. ``unit.ccss_cluster`` / ``unit.teks_cluster`` become NULLABLE. Our coverage is
     dual but not universal — single-framework units exist: the whole of U-INT
     (integer arithmetic, CCSS parks it in Grade 7) and U8 (personal financial
     literacy, no CCSS strand) are TEKS-only and carry ``ccss_cluster=None``; a
     CCSS-only unit would carry ``teks_cluster=None``. With the columns NOT NULL the
     seed below raised IntegrityError on those units. This mirrors the already-
     nullable per-lesson ``lesson.ccss_code``/``teks_code`` (TEKS_CCSS_COMPARISON.md
     / CURRICULUM_STANDARD.md; the catalog's ``uint``/``u8`` in
     ``app.domain.curriculum``). ``op.batch_alter_table`` so the ALTER is SQLite-safe
     as well as Postgres-safe (the test/round-trip path runs on SQLite).

  2. The curriculum catalog is SEEDED into ``unit`` / ``lesson`` via
     ``seed_curriculum`` — the same UPSERT-by-slug, idempotent path the app uses, run
     on a Session bound to this migration's connection and committed here. The
     catalog (``app.domain.curriculum``) is the source of truth; these rows give
     ``Assignment.unit_id`` a real FK target and let the teacher/learner surfaces
     read the curriculum from the DB (DAT.5/DAT.10). Idempotent, so re-running the
     migration chain (e.g. the round-trip test) inserts no duplicates.

Hand-written (NOT autogenerated): autogenerate cannot emit a data seed, and the
nullable ALTER needs the explicit batch op for SQLite. Mirrors the style of the
prior hand-written ``c1a7b2f4d9e0`` migration.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from app.db.seed import seed_curriculum
from sqlalchemy.orm import Session as OrmSession

# revision identifiers, used by Alembic.
revision: str = "b4f7c9a2e1d8"
down_revision: str | None = "c1a7b2f4d9e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Make the unit cluster columns nullable, THEN seed the curriculum catalog."""
    # 1. Relax the two cluster columns to nullable so TEKS-only units (which carry
    #    ccss_cluster=None) can be inserted. batch_alter_table keeps it SQLite-safe.
    with op.batch_alter_table("unit") as batch_op:
        batch_op.alter_column("ccss_cluster", existing_type=sa.String(length=32), nullable=True)
        batch_op.alter_column("teks_cluster", existing_type=sa.String(length=32), nullable=True)

    # 2. Seed the catalog onto the (now nullable-cluster) tables. The seed is the
    #    same idempotent UPSERT-by-slug the app uses; it is commit-free (caller owns
    #    the unit of work), so we drive it on a Session bound to this migration's
    #    connection and commit it ourselves.
    bind = op.get_bind()
    session = OrmSession(bind=bind)
    try:
        seed_curriculum(session)
        session.commit()
    finally:
        session.close()


def downgrade() -> None:
    """Revert the columns to NOT NULL; the seeded DATA is a documented no-op to remove.

    We do NOT delete the seeded unit/lesson rows: they are content the app reads, and
    a re-upgrade would just re-seed them, so removing them here buys nothing and risks
    cascading away an Assignment's FK target. The schema revert is real, though.

    NOTE: restoring NOT NULL on ``ccss_cluster``/``teks_cluster`` WOULD FAIL if a
    TEKS-only row (ccss_cluster=None — e.g. the seeded ``uint``/``u8``) exists, since
    those NULLs violate the restored constraint. That is acceptable: this downgrade is
    only meaningful on a DB that has no single-framework rows, and the forward
    direction is the supported path (the column is nullable for a real reason).
    """
    with op.batch_alter_table("unit") as batch_op:
        batch_op.alter_column("teks_cluster", existing_type=sa.String(length=32), nullable=False)
        batch_op.alter_column("ccss_cluster", existing_type=sa.String(length=32), nullable=False)
