"""curriculum (unit, lesson) + teacher layer (learner.role, roster, assignment)

Revision ID: c1a7b2f4d9e0
Revises: 1d435502e4db
Create Date: 2026-05-29

Wave 1 (DAT.1). Adds the curriculum skeleton and the teacher layer in one
migration:

  - ``unit`` / ``lesson`` — the curriculum tables (one Unit per CCSS/TEKS cluster,
    ordered Lessons inside it; ``lesson.kc_id`` nullable because not every lesson
    maps to a KC yet).
  - ``learner.role`` — a NOT-NULL string tag ("student"/"teacher"). Added with a
    ``server_default='student'`` so it is safe on the already-populated dev/prod
    ``learner`` table (every existing row backfills to "student"); the model carries
    a Python-side default for new rows. Identity/role never reaches the
    mastery/policy/tutor/llm path (ARCHITECTURE.md §14 invariant 8).
  - ``roster`` — teacher↔student membership (many-to-many over ``learner``).
  - ``assignment`` — a Unit assigned to a student, with a status label; UNIQUE on
    (student_id, unit_id) so "assign next unit" is an idempotent upsert.

Hand-written (NOT autogenerated, which needs a live DB at head): mirrors
``app/db/models.py`` exactly. Portable column types only, so the same migration
applies to the SQLite test DB and prod Postgres (no Postgres-only types).
``op.batch_alter_table`` is used for the ``learner.role`` add/drop so the column
change is SQLite-safe as well as Postgres-safe.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1a7b2f4d9e0"
down_revision: str | None = "1d435502e4db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the curriculum/teacher tables and add learner.role (server-default safe)."""
    # learner.role first: a NOT NULL add needs a server_default so existing rows backfill.
    with op.batch_alter_table("learner") as batch_op:
        batch_op.add_column(
            sa.Column(
                "role",
                sa.String(length=16),
                nullable=False,
                server_default="student",
            )
        )

    op.create_table(
        "unit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("ccss_cluster", sa.String(length=32), nullable=False),
        sa.Column("teks_cluster", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_unit_slug"), "unit", ["slug"], unique=True)

    op.create_table(
        "lesson",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("kc_id", sa.String(length=64), nullable=True),
        sa.Column("ccss_code", sa.String(length=32), nullable=True),
        sa.Column("teks_code", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.ForeignKeyConstraint(["unit_id"], ["unit.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lesson_slug"), "lesson", ["slug"], unique=True)
    op.create_index(op.f("ix_lesson_unit_id"), "lesson", ["unit_id"], unique=False)

    op.create_table(
        "roster",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["teacher_id"], ["learner.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["learner.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("teacher_id", "student_id", name="uq_roster_teacher_student"),
    )
    op.create_index(op.f("ix_roster_teacher_id"), "roster", ["teacher_id"], unique=False)
    op.create_index(op.f("ix_roster_student_id"), "roster", ["student_id"], unique=False)

    op.create_table(
        "assignment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("note", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["teacher_id"], ["learner.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["student_id"], ["learner.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["unit_id"], ["unit.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_id", "unit_id", name="uq_assignment_student_unit"),
    )
    op.create_index(op.f("ix_assignment_teacher_id"), "assignment", ["teacher_id"], unique=False)
    op.create_index(op.f("ix_assignment_student_id"), "assignment", ["student_id"], unique=False)
    op.create_index(op.f("ix_assignment_unit_id"), "assignment", ["unit_id"], unique=False)


def downgrade() -> None:
    """Drop the four new tables and the learner.role column (reverse order)."""
    op.drop_index(op.f("ix_assignment_unit_id"), table_name="assignment")
    op.drop_index(op.f("ix_assignment_student_id"), table_name="assignment")
    op.drop_index(op.f("ix_assignment_teacher_id"), table_name="assignment")
    op.drop_table("assignment")

    op.drop_index(op.f("ix_roster_student_id"), table_name="roster")
    op.drop_index(op.f("ix_roster_teacher_id"), table_name="roster")
    op.drop_table("roster")

    op.drop_index(op.f("ix_lesson_unit_id"), table_name="lesson")
    op.drop_index(op.f("ix_lesson_slug"), table_name="lesson")
    op.drop_table("lesson")

    op.drop_index(op.f("ix_unit_slug"), table_name="unit")
    op.drop_table("unit")

    with op.batch_alter_table("learner") as batch_op:
        batch_op.drop_column("role")
