"""teacher_reminder table (dashboard upgrade)

Revision ID: d5e8a1c63f72
Revises: b4f7c9a2e1d8
Create Date: 2026-06-01

Adds the ``teacher_reminder`` table behind the dashboard-upgrade reminders feature: a teacher's
private to-do checklist, scoped to one teacher via ``teacher_id`` (a ``learner.id`` with
``role="teacher"``). CASCADE on the FK so deleting a teacher removes their reminders.

Hand-written (NOT autogenerated, which needs a live DB at head): mirrors the ``TeacherReminder``
model in ``app/db/models.py`` exactly. Portable column types only (Integer/String/Boolean/
DateTime), so the same migration applies to the SQLite test DB and prod Postgres — the §4
portability rule the other migrations follow. Fully reversible.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5e8a1c63f72"
down_revision: str | None = "b4f7c9a2e1d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the teacher_reminder table."""
    op.create_table(
        "teacher_reminder",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=512), nullable=False),
        sa.Column("done", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["teacher_id"], ["learner.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_teacher_reminder_teacher_id"),
        "teacher_reminder",
        ["teacher_id"],
        unique=False,
    )


def downgrade() -> None:
    """Drop the teacher_reminder table."""
    op.drop_index(op.f("ix_teacher_reminder_teacher_id"), table_name="teacher_reminder")
    op.drop_table("teacher_reminder")
