"""learner locale (help-language flag, Slice 0.3)

Revision ID: e7c2a9f4b108
Revises: d5e8a1c63f72
Create Date: 2026-06-02

Adds the ``learner.locale`` column behind the bilingual-scaffold help-language flag (V2_TODO §0.3 +
owner clarification 2026-06-02): a RENDERING preference, NOT identity, that the help-mode toggle
writes and the surface/help layer reads to choose which language the avatar SPEAKS. On-screen
lesson/problem content stays English; only the avatar voice + hint text localize. Allowed values are
a validated code-side tag (``"en"`` default, ``"es-MX"`` the locked Spanish target) — a plain string,
not a DB ENUM, mirroring ``learner.role``.

Hand-written (NOT autogenerated, which needs a live DB at head): mirrors the ``Learner.locale`` model
column in ``app/db/models.py`` exactly. A NOT NULL add needs a ``server_default`` so the already-
populated dev/prod ``learner`` rows backfill to ``'en'`` — same posture as the ``learner.role`` add in
``c1a7b2f4d9e0``, and like that precedent the ``server_default`` is left in place (the model also
defaults in Python). ``op.batch_alter_table`` keeps the ALTER SQLite-safe so the SAME migration applies
to the in-memory SQLite test DB and prod Postgres (the §4 portability rule the other migrations follow).
Fully reversible.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7c2a9f4b108"
down_revision: str | None = "d5e8a1c63f72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add learner.locale (NOT NULL, server-default 'en' so existing rows backfill)."""
    with op.batch_alter_table("learner") as batch_op:
        batch_op.add_column(
            sa.Column(
                "locale",
                sa.String(length=8),
                nullable=False,
                server_default="en",
            )
        )


def downgrade() -> None:
    """Drop the learner.locale column."""
    with op.batch_alter_table("learner") as batch_op:
        batch_op.drop_column("locale")
