"""initial schema: learner, session, turn, mastery_state

Revision ID: f3426185eb03
Revises: 
Create Date: 2026-05-28 16:06:47.845454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3426185eb03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_session_id'), 'learner', ['session_id'], unique=True)
    op.create_table('mastery_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('kc_id', sa.String(length=64), nullable=False),
    sa.Column('bkt_probability', sa.Float(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('hint_count', sa.Integer(), nullable=False),
    sa.Column('unscaffolded_correct_count', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'kc_id', name='uq_mastery_learner_kc')
    )
    op.create_index(op.f('ix_mastery_state_learner_id'), 'mastery_state', ['learner_id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('route_key', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_learner_id'), 'session', ['learner_id'], unique=False)
    op.create_table('turn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=True),
    sa.Column('surface_state', sa.String(length=16), nullable=False),
    sa.Column('state_transition', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('hint_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turn_session_id'), 'turn', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turn_session_id'), table_name='turn')
    op.drop_table('turn')
    op.drop_index(op.f('ix_session_learner_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_mastery_state_learner_id'), table_name='mastery_state')
    op.drop_table('mastery_state')
    op.drop_index(op.f('ix_learner_session_id'), table_name='learner')
    op.drop_table('learner')
    # ### end Alembic commands ###
